# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familycanvas', '0005_auto_20170705_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pic',
            field=models.FileField(default=1, upload_to='media/'),
        ),
    ]
