# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familycanvas', '0006_auto_20170705_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.AddField(
            model_name='events',
            name='event_title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.DeleteModel(
            name='event_details',
        ),
    ]
