# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familycanvas', '0007_auto_20170706_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_img',
            field=models.FileField(default=1, upload_to='media/Event/'),
        ),
    ]
